# Generated by Django 3.1.7 on 2021-04-10 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aerolinea', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('NoCupos', models.IntegerField()),
                ('fechaSalida', models.DateField(max_length=200)),
                ('fechaLlegada', models.DateField(max_length=200)),
                ('horaSalida', models.TimeField(max_length=200)),
                ('horaLlegada', models.TimeField(max_length=200)),
                ('LugarSalida', models.CharField(max_length=200)),
                ('Destino', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['aerolinea'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraReserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('idVuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuluayork.vuelos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField(max_length=200)),
                ('ciudadResidencia', models.CharField(max_length=100)),
                ('tipoUsuario', models.IntegerField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
