# Generated by Django 3.1.7 on 2021-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuluayork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ciudadResidencia',
        ),
        migrations.RemoveField(
            model_name='person',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='person',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nombre',
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='tipoUsuario',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idVuelo',
            field=models.IntegerField(),
        ),
    ]
