# Generated by Django 3.1.7 on 2021-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuluayork', '0003_remove_person_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelos',
            name='InfoAdicional',
            field=models.TextField(default='Hola', max_length=200),
        ),
        migrations.AddField(
            model_name='vuelos',
            name='Requisitos',
            field=models.TextField(default='Hola', max_length=200),
        ),
    ]
