# Generated by Django 3.1.7 on 2021-04-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuluayork', '0004_auto_20210411_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
