# Generated by Django 3.1.7 on 2021-04-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuluayork', '0005_reserva_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='person',
            name='maxReserva',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='InfoAdicional',
            field=models.TextField(default='COVID 19', max_length=200),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='Requisitos',
            field=models.TextField(default='COVID 19', max_length=200),
        ),
    ]
